FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY ./app/pom.xml .
COPY ./app/mvnw .
COPY ./app/.mvn .mvn

RUN ./mvnw -q -DskipTests dependency:go-offline

COPY ./app/src src

RUN ./mvnw -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
