# build web app
FROM node:23-slim AS builder
WORKDIR /interface
COPY .env .env
COPY ./interface .
RUN npm install
RUN npm run build

# nginx
FROM nginx:alpine
COPY ./nginx/ /etc/nginx/conf.d/
COPY --from=builder /interface/dist /usr/share/nginx/html