CREATE TABLE Central_Estadual (
  nome VARCHAR(100) NOT NULL,
  estado CHAR(2) NOT NULL, 
  numero VARCHAR(11),
  rua VARCHAR(100),
  bairro VARCHAR(100),
  cidade VARCHAR(100),
  CONSTRAINT PK_CENTRAL_ESTADUAL PRIMARY KEY(estado)
);